### ISSUE TITLE
Support for referencing other variants in boards.txt

### ISSUE THREAD

**Issue by aog2000a** [arduino-cmake/arduino-cmake#49]
The **boards.txt** file allows the following syntax
`pinoccio.build.core=arduino:arduino`
to reference a core e.g. from the main Arduino SDK (see [this](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#referencing-another-core-variant-or-tool) for the detailed description). Currently arduino-cmake chokes on that syntax, since it preserves the full variable and can't find the corresponding folder.

My proposal would be to start removing the "VENDOR_ID:" part of the value, since multiple SDK locations are currently not supported (or am i worng?). That would allow locating the core by setting the `<BOARD>_CORES_PATH` variable.

Using arduino-cmake 2.0.2, Arduino IDE 1.8.5, Linux.

**Comment by MrPointer** [comment]
Sorry for being so late, have been very busy these days.

Actually this issue has been solved even before releasing **version 2.0.0**. If I recall correctly and understand your meaning well, #23 states exactly what you're trying to accomplish. 

Unfortunately our documentation is still a mess that should be corrected ASAP, and will be once I'll have more time to deal with it. For now, please relate to the [Register Custom Hardware Platforms](https://github.com/arduino-cmake/arduino-cmake/blob/develop/README.rst#advanced-options) section located just above the link (As I said, messy docs...) in the **ReadMe** file for further info.

Let me know if it's what you were looking for.

**Comment by aog2000a** [comment]
@MrPointer well, yes i'm aware of the ReadMe file and contents, but i could not manage to get cmake/build running by just "registering a custom platform". I needed not only the patch i posted above, but also several other "unexpected" variable definitions not mentioned in the docs. I've come further but it is still failing at linking, i guess i still need to find the right `set(xxxx_RECURSE True)` variables, but perhaps there is more.
Will post details later.

**Comment by aog2000a** [comment]
@MrPointer the details of the problem, as promised.

Concretely i talk about getting code for the "Pinoccio" platform to run (based on ATmega256RFR2, see https://pinocc.io/solo for  details). The platform files are: http://pinocc.io/bootstrap/pinoccio-firmware.zip 

For instance the "LEDBlink" example inside will work without issues in the Arduino IDE.

In arduino-cmake i can't get it to work "out of the box".

Steps to reproduce:

- work in /tmp/arduino:
```
    mkdir /tmp/arduino
    cd /tmp/arduino
``` 

- extract the Arduino SDK (1.8.5)
``` 
tar xfJ /tmp/arduino-1.8.5-linux64.tar.xz
``` 

- clone the arduino-cmake repo using the *develop* branch:
``` 
    git clone --branch develop https://github.com/arduino-cmake/arduino-cmake.git
``` 

- extract the Pinoccio platform files
``` 
    unzip /tmp/pinoccio-firmware.zip
``` 

- run
``` 
    export ARDUINO_SDK_PATH=/tmp/arduino/arduino-1.8.5
    export ARDUINO_CMAKE=/tmp/arduino/arduino-cmake
    export PINOCCIO_PATH=/tmp/arduino/pinoccio
``` 

- copy the LEDBlink pinoccio example, just to have it more at hand
``` 
    cp -r pinoccio/libraries/pinoccio/examples/LEDBlink blink
``` 

- switch to the blink folder and create a CMakeLists.txt file

> 
> set(PLATFORM_PATH          $ENV{PINOCCIO_PATH}/hardware/pinoccio)
> set(PLATFORM_ARCHITECTURE avr)
> 
> set(CMAKE_TOOLCHAIN_FILE $ENV{ARDUINO_CMAKE}/cmake/ArduinoToolchain.cmake)
> 
> cmake_minimum_required(VERSION 3.0)
> project(blink C CXX ASM)
> 
> print_board_list()
> print_programmer_list()
> 
> set(ARDUINO_DEFAULT_PORT /dev/pinoccio)
> set(${CMAKE_PROJECT_NAME}_BOARD "pinoccio")
> set(${CMAKE_PROJECT_NAME}_BOARD_CPU "atmega256rfr2")
> 
> generate_arduino_firmware(blink
> 		SKETCH LEDBlink.ino
> 		NO_AUTOLIBS)
> 

- run
``` 
    mkdir build
    cd build
    cmake ..
``` 

With the above CMake file i get immediately:

>
> -- Arduino SDK version 1.8.5-2017.01.09: /tmp/arduino/arduino-1.8.5
> CMake Error at /tmp/arduino/arduino-cmake/cmake/Platform/Core/VariableValidator.cmake:17 (message):
>   ARDUINO_CORES_PATH not set: Invalid Arduino SDK path
>   (/tmp/arduino/arduino-1.8.5).
>

- so, i define the requested variable, just to see that it wants ARDUINO_BOOTLOADERS_PATH. It goes on reqesting several variables, until I end up with the following CMakeLists.txt file:

>
> set(ARDUINO_CORES_PATH       $ENV{ARDUINO_SDK_PATH}/hardware/arduino/avr/cores)
> set(ARDUINO_BOOTLOADERS_PATH $ENV{ARDUINO_SDK_PATH}/hardware/arduino/avr/bootloaders)
> set(ARDUINO_BOARDS_PATH      $ENV{ARDUINO_SDK_PATH}/hardware/arduino/avr/boards.txt)
> set(ARDUINO_PROGRAMMERS_PATH $ENV{ARDUINO_SDK_PATH}/hardware/arduino/avr/programmers.txt)
> 
> set(PLATFORM_PATH         $ENV{PINOCCIO_PATH}/hardware/pinoccio)
> set(PLATFORM_ARCHITECTURE avr)
> 
> set(CMAKE_TOOLCHAIN_FILE $ENV{ARDUINO_CMAKE}/cmake/ArduinoToolchain.cmake)
> 
> [... MORE LINES ...]
> 

At that step i get:

> 
> -- Generating blink
> CMake Error at /tmp/arduino/arduino-cmake/cmake/Platform/Core/Libraries/CoreLibraryFactory.cmake:22 (find_sources):
>   find_sources Function invoked with incorrect arguments for function named:
>   find_sources
> 

However, when I edit the file `/tmp/arduino/pinoccio/hardware/pinoccio/avr/boards.txt` and modify the line

> pinoccio.build.core=arduino:arduino

to read:

> pinoccio.build.core=arduino

then it goes one step further. BUT: it still cannot find the sources for the core, since the pinoccio hardware folder does not include any "core" folder (it uses arduino's default cores). However, if i add the an extra variable for the core:

> set(PINOCCIO_CORES_PATH $ENV{ARDUINO_SDK_PATH}/hardware/arduino/avr/cores)

the cmake step is successful :)

**Comment by aog2000a** [comment]
Summary:

- i needed my patch or modifying the boards.txt file to remove the "arduino:" piece.
- as soon as i define `PLATFORM_PATH` i needed to also define all 4 variables `ARDUINO_*_PATH`, even if the `ARDUINO_SDK_PATH` variable was still defined
- i needed to define `PINOCCIO_CORES_PATH` explicitly, i would expect that `ARDUINO_CORES_PATH` is used as fall back location

**Comment by noseglasses** [comment]
> The boards.txt file allows the following syntax
pinoccio.build.core=arduino:arduino
to reference a core e.g. from the main Arduino SDK (see this for the detailed description). Currently arduino-cmake chokes on that syntax, since it preserves the full variable and can't find the corresponding folder.

That's odd as this problem was addressed by #19. The relevant change was kindly considered by MrPointer during his v2.0 refactoring. It ended up [here](https://github.com/arduino-cmake/arduino-cmake/blob/e377f9ca58313d34fcbf3a9cb0d550ff24f7b43e/cmake/Platform/Initialization/RegisterSpecificHardwarePlatform.cmake#L92). 

@aog2000a: Do you register the pinoccio platform via `cmake/Platform/Initialization/RegisterSpecificHardwarePlatform.cmake`? 
I am using a custom hardware as well that defines `model01.build.core=arduino:arduino` in `boards.txt and it works for me.

**Comment by aog2000a** [comment]
@noseglasses  No, i just set the PLATFORM_PATH variable as mentioned in the README. My CMakeLists.txt has this piece:

> set(PLATFORM_PATH $ENV{PINOCCIO_PATH}/hardware/pinoccio)
> set(PLATFORM_ARCHITECTURE avr)
>
> set(CMAKE_TOOLCHAIN_FILE $ENV{ARDUINO_CMAKE}/cmake/ArduinoToolchain.cmake)

I actually debugged the issue by adding MESSAGE() lines in the arduino-cmake code, and could see that the "arduino:arduino" value in build.core was causing the 
`find_sources(CORE_SRCS ${BOARD_CORE_PATH} True)`
line in Platform/Core/Libraries/CoreLibraryFactory.cmake to fail.

**Comment by noseglasses** [comment]
Please have a try with including `cmake/Platform/Initialization/RegisterSpecificHardwarePlatform.cmake` to register your custom hardware.

**Comment by MrPointer** [comment]
@aog2000a You're right, currently there **is** a problem making it work for a platform like **pinoccio** that doesn't define any cores of it's own but rather uses the Arduino's ones.
I'm currently working on a fix that will default to the Arduino hardware platform if required parts such as `core` and `bootloader` aren't found in the given custom platform.

**Comment by MrPointer** [comment]
### Update
I've managed to add some code to resolve 3rd party platforms to the default **Arduino** platform automatically if required to, and it works perfectly when reloading CMake, however, fails on the build.
I don't have much time this weekend to address it further, maybe not even to share the build's failure reason. I hope that will change 😃

**Comment by noseglasses** [comment]
> I've managed to add some code to resolve 3rd party platforms to the default Arduino platform automatically if required to

@MrPointer: My PR #55 contains a [commit](https://github.com/arduino-cmake/arduino-cmake/pull/55/commits/f441feaec7b1503eb558e985648007fb51435c81#diff-07edf1f8f0cf9043ccebd5dace3ac70cR45) that maybe related as it reads `platform.txt` (the very bottom of the commit in `RegisterSpecificHardwarePlatform.cmake`). If your approach is better, I will remove this commit.

**Comment by MrPointer** [comment]
@noseglasses I took a look in that PR but it doesn't seem related to the issues I'm trying to solve.
Finally I got some time to finalize the code base so others can look at it and help further. Please take a look at my [Private Fork](https://github.com/MrPointer/arduino-cmake/tree/feature/3rd-party-platform-support) containing my work on the subject.

Basically I've added code that treats all 3rd party platforms as if they provide the entire 'package', but if not, like the **pinoccio** platform for example, it defaults to the native **Arduino SDK** in the missing parts. 
However, something's not right and I just can't figure out what - The CMake generation is fine yet the build is failing with the `fatal error: Arduino.h: No such file or directory` message, failing in the `IPAddress.cpp` file linkage. I've already encountered the error multiple times in the past, but never really understood what solved it...

**Comment by adolfogc** [comment]
Hello. I'm also having this issue, only that I'm using the [Controllino](https://controllino.biz) platform. I was trying to get around this issue using the workaround mentioned by @aog2000a in a previous comment, but it still isn't working. Below are the contents of my CMakeLists.txt file:
```cmake
cmake_minimum_required(VERSION 3.10)

include(cmake/DownloadProject.cmake) # https://github.com/Crascit/DownloadProject

if(APPLE)
download_project(PROJ arduino-ide
                 URL https://downloads.arduino.cc/arduino-1.8.3-macosx.zip
                 URL_HASH SHA512=20b2fe3370ef0314c8c4dabedbbe88f814eae9444a53b32d68de5e6b7d612b6aa7b38928ae4f47084c8ad916e87cb24634e28a4a7fe0de39f08eec29a309263f
                 TLS_VERIFY true
                 DOWNLOAD_DIR "Downloads"
                 "UPDATE_DISCONNECTED 1")
elseif(LINUX)
download_project(PROJ arduino-ide
                 URL https://downloads.arduino.cc/arduino-1.8.3-linux64.tar.gz
                 URL_HASH SHA512=039c5d6f604beddb3be66c526a7abd6262aeb46292ab7906ae8f165bed6119ce7a1b0ca47253e381b2524ccd56d5a10b39742a433db536ba6dc8d4a60795b72f
                 TLS_VERIFY true
                 DOWNLOAD_DIR "Downloads"
                 "UPDATE_DISCONNECTED 1")
endif()

download_project(PROJ controllino-bsp
                 URL https://github.com/CONTROLLINO-PLC/CONTROLLINO_Library/archive/2.0.1.tar.gz
                 URL_HASH SHA512=9371139c41923c177ff104b8959c0b511768d8cb4e222779b91b4a5bc71ec1101f0a68c88d500c4fb1184176bc5166832889d6c8c7e69ee086aa993f53fd1ee7
                 TLS_VERIFY true
                 DOWNLOAD_DIR "Downloads"
                 "UPDATE_DISCONNECTED 1")

download_project(PROJ arduino-cmake
                 URL https://github.com/arduino-cmake/arduino-cmake/archive/v2.0.2.tar.gz
                 URL_HASH SHA512=7071cbcb681e5f64be81c3717a309e70e4730b5e39c67ccdc4ef9e0d58ee6e59e2683da236b452a60a88bddfd32807b07c067cf434fed7a004572270b2522048
                 TLS_VERIFY true
                 DOWNLOAD_DIR "Downloads"
                 "UPDATE_DISCONNECTED 1")

execute_process(COMMAND mkdir -p hardware/controllino)
execute_process(COMMAND unzip -u ${controllino-bsp_SOURCE_DIR}/Boards/ControllinoHW.zip -d hardware/controllino)

set(ARDUINO_SDK_PATH "${arduino-ide_SOURCE_DIR}/Contents/Java")
set(CONTROLLINO_BSP_SOURCE ${controllino-bsp_SOURCE_DIR})

set(PLATFORM_PATH "${CMAKE_CURRENT_SOURCE_DIR}/hardware/controllino")
set(PLATFORM_ARCHITECTURE "avr")
set(ARDUINO_CORES_PATH "${CMAKE_CURRENT_SOURCE_DIR}/hardware/controllino/avr/cores")
set(ARDUINO_BOOTLOADERS_PATH "${controllino-bsp_SOURCE_DIR}/Bootloaders/MAXI")
set(ARDUINO_BOARDS_PATH "${CMAKE_CURRENT_SOURCE_DIR}/hardware/controllino/avr/boards.txt")
set(ARDUINO_PROGRAMMERS_PATH "${CMAKE_CURRENT_SOURCE_DIR}/hardware/controllino/avr/programmers.txt")

set(CMAKE_TOOLCHAIN_FILE ${arduino-cmake_SOURCE_DIR}/cmake/ArduinoToolchain.cmake)

project(MyProject C CXX ASM)

print_board_list()
print_programmer_list()

add_subdirectory(myproject)
```

One thing to note is that neither `print_board_list()` or `print_programmer_list()`  produce output.

The error I get is the following one:

```
-- Generating controllino_lib
CMake Error at build/arduino-cmake-src/cmake/Platform/Core/BoardPropertiesReader.cmake:59 (message):
  Board info not found: BoardName='controllino_maxi' BoardCPU=''
  PropertyName='build.core'
Call Stack (most recent call first):
  build/arduino-cmake-src/cmake/Platform/Core/Libraries/CoreLibraryFactory.cmake:16 (_get_board_property)
  build/arduino-cmake-src/cmake/Platform/Generation/ArduinoLibraryGenerator.cmake:28 (make_core_library)
```

Can someone point me in the right direction for the current workaround?

Thanks in advance.
